ARG BASE_IMAGE=dolphinjiang/rust-musl-builder:latest
FROM ${BASE_IMAGE} AS builder
ADD --chown=rust:rust . ./
RUN cargo build --release

# https://github.com/kjarosh/latex-docker
FROM kjarosh/latex:2023.1-small
LABEL org.reddwarf.image.authors="jiangtingqiang@gmail.com"

ENV LANG=en_US.UTF-8 \
    LC_ALL=en_US.UTF-8 \
    TZ=Asia/Shanghai

WORKDIR /app
ENV ROCKET_ADDRESS=0.0.0.0
COPY --from=builder /home/rust/src/settings-production.toml /app/settings.toml
COPY --from=builder /home/rust/src/script /app/
COPY --from=builder /home/rust/src/target/x86_64-unknown-linux-musl/release/cv-render /app/
RUN mkdir -p /usr/share/fonts/ && mkdir -p /app/config/ && mkdir -p /root/.ssh
COPY --from=builder /home/rust/src/texmf/tex/latex/ /opt/texlive/texmf-local/tex/latex/
COPY ./config/font /usr/share/fonts/
COPY --from=builder /home/rust/src/log4rs.yaml /app/config/
COPY --from=builder /home/rust/src/config/ssh/known_hosts /root/.ssh/
RUN tlmgr install ctex moderncv fontawesome5 fontawesome nth\ 
    academicons multirow arydshln titlesec enumitem makecell \
    tcolorbox environ tikzfill csquotes xifthen ifmtarg tex-gyre && \
    apk update && \
    apk add rsync openssh sshpass fontconfig && \
    chmod +x cv-render && texhash
CMD ["sh","./startup-app.sh"]