# https://doc.rust-lang.org/cargo/reference/config.html
[alias]
b = "build"

[build]
rustflags = [
    "-L", "./src/so"
    ]
incremental = true

[source.crates-io]
replace-with = 'tuna'

[source.tuna]
registry = "sparse+https://mirrors.tuna.tsinghua.edu.cn/crates.io-index/"